apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homarr-secrets
  namespace: homarr
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: homarr-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: homarr
