apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homarr-secrets
  namespace: homarr
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: homarr-secrets
    creationPolicy: Owner
  data:
  - secretKey: SECRET_ENCRYPTION_KEY
    remoteRef:
      key: homarr
      property: SECRET_ENCRYPTION_KEY
  - secretKey: DATABASE_PASSWORD  
    remoteRef:
      key: homarr
      property: DATABASE_PASSWORD
  - secretKey: JWT_SECRET
    remoteRef:
      key: homarr
      property: JWT_SECRET
