apiVersion: v1
kind: Secret
metadata:
  name: homarr-secrets
  namespace: homarr
type: Opaque
stringData:
  SECRET_ENCRYPTION_KEY: "kZaDzM9xkrEUdI+yv7UhXeVDT3ZHIvNJ"
  JWT_SECRET: "3fa6e2c3ce70d1488d7ddb56680321717e5ee660861887121fb2786d103b0474"
