apiVersion: apps/v1
kind: Deployment
metadata:
  name: homarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homarr
  template:
    metadata:
      labels:
        app: homarr
    spec:
      serviceAccountName: homarr-sa
      containers:
        - name: homarr
          image: ghcr.io/homarr-labs/homarr:latest
          ports:
            - containerPort: 7575
          env:
        - name: SECRET_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: homarr-secrets
              key: SECRET_ENCRYPTION_KEY
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: homarr-secrets
              key: DATABASE_PASSWORD
              optional: true
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: homarr-secrets
              key: JWT_SECRET
              optional: true
