apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-29"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: 0.14.*
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-28"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  source:
    repoURL: https://github.com/myfri09/homelab
    targetRevision: main
    path: infrastructure/staging/metallb/config
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
