apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkding-secrets
  namespace: linkding
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: linkding-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: homelab/linkding
        property: POSTGRES_PASSWORD
    - secretKey: SECRET_KEY
      remoteRef:
        key: homelab/linkding
        property: SECRET_KEY
