apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkding-secrets
  namespace: linkding
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: linkding-secrets
    creationPolicy: Owner
  data:
    - secretKey: SECRET_ENCRYPTION_KEY
      remoteRef:
        key: linkding
        property: SECRET_ENCRYPTION_KEY
