apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkding-secrets
  namespace: linkding
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: linkding-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: linkding
