apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-27"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 32.*
    helm:
      values: |
        service:
          type: LoadBalancer
        ingressClass:
          enabled: true
          isDefaultClass: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
