---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homarr-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/myfri09/homelab
    targetRevision: main
    path: apps/staging/homarr
  destination:
    server: https://kubernetes.default.svc
    namespace: homarr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkding-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/myfri09/homelab
    targetRevision: main
    path: apps/staging/linkding
  destination:
    server: https://kubernetes.default.svc
    namespace: linkding
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
