apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-helm-values
  namespace: vault
data:
  values.yaml: |
    server:
      dataStorage:
        enabled: true
        storageClass: local-path
        size: 10Gi
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: vault.myfri09.lan
            paths: [/]
        tls:
          - hosts:
              - vault.myfri09.lan
            secretName: vault-tls
      dev:
        enabled: false
      standalone:
        enabled: true
        config: |
          ui = true
          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }
          storage "file" {
            path = "/vault/data"
          }
    ui:
      enabled: true
