apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      serviceAccountName: linkding-sa
      containers:
        - name: linkding
          image: sissbruecker/linkding:latest
          ports:
            - containerPort: 9090
          env:
            - name: SECRET_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: linkding-secrets
                  key: SECRET_ENCRYPTION_KEY
          volumeMounts:
            - name: linkding-data
              mountPath: /etc/linkding/data
          readinessProbe:
            httpGet:
              path: /login
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /login
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 20
      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data-pvc
