apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      serviceAccountName: linkding-sa
      containers:
        - name: linkding
          image: sissbruecker/linkding:latest
          ports:
            - containerPort: 9090
          env:
        - name: SECRET_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: linkding-secrets
              key: SECRET_ENCRYPTION_KEY
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: linkding-secrets
              key: POSTGRES_PASSWORD
              optional: true
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: linkding-secrets
              key: REDIS_PASSWORD
              optional: true

          volumeMounts:
            - name: linkding-data
              mountPath: /etc/linkding/data
      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data-pvc
