apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-26"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage
  source:
    repoURL: https://charts.rancher.io
    chart: local-path-provisioner
    targetRevision: 0.0.*
    helm:
      values: |
        storageClass:
          defaultClass: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
